# CodeBuild project Buildspec to get information about serverless resources
# via Serverless Framework
#
# required environment variables
#
#  ENVIRONMENT                = Environment

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      # nodejs: 10  # nodejs 10.x already included (choices: 8, 10)
    commands:
      - phase="INSTALL"
      - npm install --global serverless
      - npm install
      - node --version
      - python --version
      - serverless --version
    finally:
      - echo "$phase - phase COMPLETE"
  pre_build:
    commands:
      - phase="PRE_BUILD"
      # get info about Serverless infra
      - echo "$phase - testing serverless configurations"
      - bash sls_control.sh -a info -s $ENVIRONMENT -v -x
      - echo "$phase - all serverless configuration tests PASSED"
    finally:
      - echo "$phase - phase COMPLETE"
