service: aws-cicd

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  memorySize: 128
  timeout: 3

functions:
  logger:
    handler: handler.logger
    events:
      - http:
          path: message
          method: get

resources:
  Description: 'Creates Serverless resources: Lambda function(s), layer(s) and REST API Gateway'