AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Hello World learning app for SAM
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs12.x
    Timeout: 5
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
  EventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: logger.handler
      Timeout: 3
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get
        FileUpload:
          Type: S3
          Properties:
            Bucket:
              Ref: S3Bucket
            Events: s3:ObjectCreated:*
      CodeUri: s3://ag-devops-sandbox/sam/79badc0b906b08f31f66d2e81bc505ec
  NumberAdder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add.handler
      Events:
        PostAdd:
          Type: Api
          Properties:
            Path: /add
            Method: post
      CodeUri: s3://ag-devops-sandbox/sam/79badc0b906b08f31f66d2e81bc505ec
