---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates an Load Balancer Listener'


Parameters:

  AcmCertArnDefault:
    Default: ''
    Description: 'ARN of ACM Certificate. (required for HTTPS protocol)'
    Type: String

  # Additional certs to attach to the Listener
  AcmCertArn2: {Default: '', Type: String}
  AcmCertArn3: {Default: '', Type: String}
  AcmCertArn4: {Default: '', Type: String}
  AcmCertArn5: {Default: '', Type: String}

  LbArn:
    Description: 'ARN of Load Balancer'
    Type: String

  DefaultTargetGroupArn:
    Description: 'ARN of the default Target Group'
    Type: String

  ListeningPort:
    Description: 'Load Balancer Listening Port'
    Type: Number

  ListeningProtocol:
    AllowedValues: [HTTP, HTTPS]
    Description: 'Listening Protocol (HTTP or HTTPS)'
    Type: String

  SslPolicy:
    # docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html
    #Default: ELBSecurityPolicy-TLS-1-1-2017-01
    Default: ELBSecurityPolicy-FS-2018-06
    Description: 'Security policy defining ciphers and protocols'
    Type: String


Conditions:

  ProtoIsHttps: !Equals [!Ref ListeningProtocol, HTTPS]
  AddionalCertsToAdd: !Or
    - !Not [!Equals [!Ref AcmCertArn2, '']]
    - !Not [!Equals [!Ref AcmCertArn3, '']]
    - !Not [!Equals [!Ref AcmCertArn4, '']]
    - !Not [!Equals [!Ref AcmCertArn5, '']]
  AcmCert2Provided: !Not [!Equals [!Ref AcmCertArn2, '']]
  AcmCert3Provided: !Not [!Equals [!Ref AcmCertArn3, '']]
  AcmCert4Provided: !Not [!Equals [!Ref AcmCertArn4, '']]
  AcmCert5Provided: !Not [!Equals [!Ref AcmCertArn5, '']]

Resources:

  Certificates:
    Condition: AddionalCertsToAdd
    Properties:
      Certificates:
        - !If
          - AcmCert2Provided
          - CertificateArn: !Ref AcmCertArn2
          - !Ref 'AWS::NoValue'
        - !If
          - AcmCert3Provided
          - CertificateArn: !Ref AcmCertArn3
          - !Ref 'AWS::NoValue'
        - !If
          - AcmCert4Provided
          - CertificateArn: !Ref AcmCertArn4
          - !Ref 'AWS::NoValue'
        - !If
          - AcmCert5Provided
          - CertificateArn: !Ref AcmCertArn5
          - !Ref 'AWS::NoValue'
      ListenerArn: !Ref LbListener
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate

  LbListener:
    Properties:
      Certificates: !If
        - ProtoIsHttps
        - - CertificateArn: !Ref AcmCertArnDefault
        - !Ref 'AWS::NoValue'
      DefaultActions:
        - TargetGroupArn: !Ref DefaultTargetGroupArn
          Type: forward
      LoadBalancerArn: !Ref LbArn
      Port: !Ref ListeningPort
      Protocol: !Ref ListeningProtocol
      SslPolicy: !If
        - ProtoIsHttps
        - !Ref SslPolicy
        - !Ref 'AWS::NoValue'
    Type: AWS::ElasticLoadBalancingV2::Listener


Outputs:

  LbListenerArn:
    Description: ARN of the Listener
    Export: {Name: !Sub '${AWS::StackName}-LbListenerArn'}
    Value: !Ref LbListener
