- hosts: localhost
  connection: local
  gather_facts: no
  vars:
  pre_tasks:
    - set_fact:
      args:
        success_msg: "{{ item }} - the deploymnet completed!"
      with_random_choice:
        - "Yes"
        - "OMG"
        - "WOW"
        - "Whew"
    - set_fact:
      args:
        fail_msg: "{{ item }} - the deploymnet FAILED!"
      with_random_choice:
        - "NO"
        - "Crap"
        - "WUT"

  tasks:
    - debug: var=success_msg
    - debug: var=fail_msg
