---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates API Gateway OPTIONS method that defines the parameters and body that clients must send in their requests'


Parameters:

  ResourceId:
    Description: 'The ID of an API Gateway resource. For root resource methods, specify the RestApi root resource ID'
    Type: String

  RestApiId:
    Description: 'The ID of the RestApi resource in which API Gateway creates the method.'
    Type: String


Resources:

  ApiMethodOptions:
    Properties:
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
          StatusCode: 200
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
          StatusCode: 200
      ResourceId: !Ref ResourceId
      RestApiId: !Ref RestApiId
    Type: AWS::ApiGateway::Method


Outputs:

  MethodId:
    Description: 'ID of the API Method'
    Export: {'Name': !Sub '${AWS::StackName}-MethodId'}
    Value: !Ref ApiMethodOptions
