---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates EC2 Security Group for Batch Servers'


Parameters:

  GroupDescription:
    Description: 'A description of the security group'
    Type: String

  GroupName:
    Description: 'A name for the security group'
    Type: String

  VpcId:
    Description: 'VPC ID to place security groups'
    Type: 'AWS::EC2::VPC::Id'


Resources:

  Ec2Sg:
    Properties:
      GroupName: !Ref GroupName
      GroupDescription: !Ref GroupDescription
      SecurityGroupIngress:
        - {FromPort: 3389, ToPort: 3389, IpProtocol: tcp, CidrIp: 70.168.144.52/32, Description: RDP from Onica Irvine}
        - {FromPort: 3389, ToPort: 3389, IpProtocol: tcp, CidrIp: 73.60.127.67/32, Description: RDP from Infogix}
      Tags:
        - {Key: Name, Value: !Ref GroupName}
      VpcId: !Ref VpcId
    Type: AWS::EC2::SecurityGroup


Outputs:

  SgId:
    Description: The ID of the security group
    Export: {Name: !Sub '${AWS::StackName}-SgId'}
    Value: !GetAtt Ec2Sg.GroupId
