---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates an AWS SNS topic and subscriptions to it'


Parameters:

  DisplayName:
    Description: 'A developer-defined string that can be used to
      identify this SNS topic. Required for SMS subscriptions
      (up to 10 characters long)'
    MaxLength: 10
    Type: String

  TopicName:
    Description: 'Name of the SNS topic'
    Type: String


Resources:

  SnsTopic:
    Properties:
      DisplayName: !Ref DisplayName
      # Un-Comment to add subscriptions
      # Subscription:
      #   Examples of subscriptions that can be added
      #   # applications (i.e. mobile apps - e.g. Apple push notifications)
      #   - Endpoint: arn:aws:sns:us-west-2:111122223333:app/APNS_SANDBOX/mypushappname/uuid
      #     Protocol: application
      #   - Endpoint: user@example.com
      #     Protocol: email
      #   - Endpoint: http://example.com
      #     Protocol: http
      #   - Endpoint: https://example.com
      #     Protocol: https
      #     # for lambda function processing
      #   - Endpoint: arn:aws:lambda:us-east-1:123456789012:function:lambda-name
      #     Protocol: lambda
      #     # for SMS enabled devices
      #   - Endpoint: 1-123-456-7890
      #     Protocol: sms
      #     # for SQS processing
      #   - Endpoint: arn:aws:sqs:us-east-1:456683474740:d3s-bulkload-legacydev.fifo
      #     Protocol: sqs
      TopicName: !Ref TopicName
    Type: AWS::SNS::Topic


Outputs:

  TopicArn:
    Description: ARN of the SNS topic
    Export: {'Name': !Sub '${AWS::StackName}-TopicArn'}
    Value: !Ref SnsTopic

  TopicName:
    Description: Name of the SNS topic
    Export: {'Name': !Sub '${AWS::StackName}-TopicName'}
    Value: !GetAtt SnsTopic.TopicName
